name: agelapse
description: A powerful tool for creating stabilized aging timelapses.
publish_to: 'none'

version: 1.1.4+13

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.1+1
  flutter_native_splash: ^2.4.1
  flutter_native_timezone: ^2.0.0
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  flutter_image_compress: ^2.3.0
  animated_bottom_navigation_bar: ^1.3.3
  wakelock_plus: ^1.2.5
  archive: ^3.6.1
  flutter_archive: ^6.0.3
  async_zip: ^0.1.0
  sqflite: ^2.3.3+1
  provider: ^6.1.2
  heif_converter: ^1.0.0
  flutter_email_sender: ^6.0.3
  camera: ^0.11.0+1
  smooth_page_indicator: ^1.2.0
  chewie: ^1.8.1
  vibration: ^1.9.0
  video_player: ^2.9.1
  path_provider: ^2.1.3
  saver_gallery: ^3.0.5
  file_picker: ^8.0.6
  wechat_assets_picker: ^9.1.0
  exif: ^3.3.0
  intl: ^0.19.0
  ffmpeg_kit_flutter_video: 6.0.3-LTS
  share_plus: ^9.0.0
  image: ^4.2.0
  google_mlkit_face_detection: ^0.9.0
  google_mlkit_pose_detection: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  fonts:
    - family: CedarvilleCursive
      fonts:
        - asset: fonts/CedarvilleCursive-Regular.ttf
  uses-material-design: true

  assets:
    - assets/images/
    - assets/ghost-custom.svg
    - assets/relax.svg

flutter_native_splash:
  color: "#2b2b2b"
  image: assets/images/splash/logo.png
  android_12:
    color: "#2b2b2b"

